/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tum_andrive_Andrive */


#ifndef _Included_tum_andrive_LaneDetection_LaneDetector
#define _Included_tum_andrive_LaneDetection_LaneDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tum_andrive_lanedetection_LaneDetector
 * Method:    mainDelegate
 * Signature: (JJ)V
 */

JNIEXPORT void JNICALL Java_tum_andrive_lanedetection_LaneDetector_mainDelegate
  (JNIEnv *env, jobject obj, jlong in, jlong out, jint houghValue);


#ifdef __cplusplus
}
#endif
#endif
