/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class tum_andrive_Andrive */

#ifndef _Included_tum_andrive_LaneDetection_TestMain
#define _Included_tum_andrive_LaneDetection_TestMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tum_andrive_lanedetection_TestMain
 * Method:    nativeThreshold
 * Signature: (JJ)V
 */

//JNIEXPORT jobjectArray JNICALL Java_tum_andrive_lanedetection_TestMain_main
  //(JNIEnv *, jobject, jlong, jlong, jobjectArray);


JNIEXPORT jobjectArray JNICALL Java_tum_andrive_lanedetection_TestMain_mainExecute
(JNIEnv *env, jobject obj, jobjectArray objArray);


#ifdef __cplusplus
}
#endif
#endif
